version: "3.9"
services:
    agentdvr:
        restart: always
        build: 
            context: .
            dockerfile: dockerfile
        ports:
        - 8090:8090
        - 3478:3478/udp
        - 50000-50010:50000-50010/udp
